# Generated by Django 3.2.25 on 2024-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=1, default=9.5, max_digits=4)),
                ('colorway', models.CharField(default='white', max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
