# Generated by Django 4.2.14 on 2024-07-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerheads', '0002_sneaker_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='photo',
            new_name='image',
        ),
    ]
